
# avoids building a PR twice, once for a branch and another due to the PR status
# see: https://github.com/travis-ci/travis-ci/issues/1147#issuecomment-160820262
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

language: generic

jobs:
  include:
    - stage: Java tests
      script:
        - curl -O https://www.antlr.org/download/antlr-4.7.1-complete.jar
        # generate java
        - java -jar antlr-4.7.1-complete.jar -Xexact-output-dir -o src/java/parcera/antlr -package parcera.antlr -Dlanguage=Java -no-listener -no-visitor src/Clojure.g4
        # now we can actually proceed with clojure code
        - lein do clean, compile, check, eastwood
        - lein trampoline test
        - lein trampoline test :benchmark
        # generate javascript
        - java -jar antlr-4.7.1-complete.jar -Xexact-output-dir -o src/javascript/parcera/antlr -package parcera.antlr -Dlanguage=JavaScript -no-listener -no-visitor src/Clojure.g4
        - nvm install 10.10 && nvm use 10.10 && lein trampoline cljsbuild test
    - stage: Js tests
      script:
        - curl -O https://www.antlr.org/download/antlr-4.7.1-complete.jar
        # generate javascript
        - java -jar antlr-4.7.1-complete.jar -Xexact-output-dir -o src/javascript/parcera/antlr -package parcera.antlr -Dlanguage=JavaScript -no-listener -no-visitor src/Clojure.g4
        # pre-bundle javascript
        - npx webpack --config ./resources/webpack.config.js
        - nvm install 10.10 && nvm use 10.10 && lein trampoline cljsbuild test

    - stage: Release
      if: tag IS present
      script:
        - curl -O https://www.antlr.org/download/antlr-4.7.1-complete.jar
        # generate java
        - java -jar antlr-4.7.1-complete.jar -Xexact-output-dir -o src/java/parcera/antlr -package parcera.antlr -Dlanguage=Java -no-listener -no-visitor src/Clojure.g4
        - lein do javac, compile, check
        # todo: include js in out jar
      deploy:
        - provider: script
          script: lein deploy clojars
          skip_cleanup: true
          on:
            tags: true
